version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - mkdir --parents _readthedocs/html/
    - python3 dev/generate-redirects.py docs/redirects.json _readthedocs/html/
    - |
      cat <<- 'EOF' > _readthedocs/html/robots.txt
      User-agent: *
      Allow: /
      EOF
